In [1]:
## This notebook uses standard pandas to checkout the output
# pip install fastparquet pyarrow

In [12]:
import pandas as pd

def read_parquet_file(file_path):
    """
    Reads a Parquet file and prints the DataFrame.

    Parameters:
    file_path (str): The path to the Parquet file.
    """
    try:
        # Read the Parquet file
        df = pd.read_parquet(file_path)

        # Print the DataFrame
        print("Data from the Parquet file:")
        display(df.head(5))
    except Exception as e:
        print(f"An error occurred: {e}")
    return df

In [13]:

file_path = 'output/intermediate_table/account_details'
df = read_parquet_file(file_path)

Data from the Parquet file:

,account_id,company_name,company_address,contact_person,contact_phone,invoice_id,date_issued,days_since_invoice,ingest_ts
0,1,Apex Auto Group,"58987 Crystal Terrace\nWest Katherine, AR 24780",Brent Barnes,001-470-476-0187x922,1,2021-01-03,1297,2024-07-23 08:28:52.407561
1,1,Apex Auto Group,"58987 Crystal Terrace\nWest Katherine, AR 24780",Brent Barnes,001-470-476-0187x922,2,2020-03-19,1587,2024-07-23 08:28:52.407561
2,1,Apex Auto Group,"58987 Crystal Terrace\nWest Katherine, AR 24780",Brent Barnes,001-470-476-0187x922,3,2021-01-14,1286,2024-07-23 08:28:52.407561
3,1,Apex Auto Group,"58987 Crystal Terrace\nWest Katherine, AR 24780",Brent Barnes,001-470-476-0187x922,4,2020-05-20,1525,2024-07-23 08:28:52.407561
4,1,Apex Auto Group,"58987 Crystal Terrace\nWest Katherine, AR 24780",Brent Barnes,001-470-476-0187x922,5,2020-05-29,1516,2024-07-23 08:28:52.407561

In [14]:
df[df["account_id"] == "1"]

Empty DataFrame
Columns: [account_id, company_name, company_address, contact_person, contact_phone, invoice_id, date_issued, days_since_invoice, ingest_ts]
Index: []

In [15]:

file_path = 'output/intermediate_table/invoice_details'
read_parquet_file(file_path)

Data from the Parquet file:

,invoice_id,account_id,date_issued,item_id,quantity,item_name,item_cost_price,item_retail_price,total_sale_value,total_cost_value
0,1,1,2021-01-03,1-60559-539-X,4,VehicleMarketPro,1.63507387,31.36233077,125.449323,6.540295
1,1,1,2021-01-03,1-944086-93-5,3,AutoPromoBlitz,4.577482221,27.59476372,82.784291,13.732447
2,2,1,2020-03-19,0-254-97850-9,2,EngineAdPro,32.35212531,38.12985263,76.259705,64.704251
3,2,1,2020-03-19,1-60559-539-X,1,VehicleMarketPro,1.63507387,31.36233077,31.362331,1.635074
4,2,1,2020-03-19,0-575-31913-5,4,MotorAdFusion,18.36120796,210.9186898,843.674759,73.444832

,invoice_id,account_id,date_issued,item_id,quantity,item_name,item_cost_price,item_retail_price,total_sale_value,total_cost_value
0,1,1,2021-01-03,1-60559-539-X,4,VehicleMarketPro,1.63507387,31.36233077,125.449323,6.540295
1,1,1,2021-01-03,1-944086-93-5,3,AutoPromoBlitz,4.577482221,27.59476372,82.784291,13.732447
2,2,1,2020-03-19,0-254-97850-9,2,EngineAdPro,32.35212531,38.12985263,76.259705,64.704251
3,2,1,2020-03-19,1-60559-539-X,1,VehicleMarketPro,1.63507387,31.36233077,31.362331,1.635074
4,2,1,2020-03-19,0-575-31913-5,4,MotorAdFusion,18.36120796,210.9186898,843.674759,73.444832
...,...,...,...,...,...,...,...,...,...,...
55932,10252,200,2020-06-11,0-9968491-0-6,4,MotorPromoElite,30.80013459,65.2611619,261.044648,123.200538
55933,10252,200,2020-06-11,0-19-815284-1,4,AutoAdBoost,13.38563993,81.67170578,326.686823,53.542560
55934,10253,200,2020-05-20,1-69029-927-4,4,AutoPromoSpot,2.769909948,63.80289597,255.211584,11.079640
55935,10253,200,2020-05-20,0-8208-9890-2,3,TurboPromoMaster,28.97750736,59.57333241,178.719997,86.932522
55936,10253,200,2020-05-20,0-02-530216-7,1,EngineAdMax,44.83229992,150.9138468,150.913847,44.832300

In [16]:

file_path = 'output/fact_table/fact_sales_processed'
read_parquet_file(file_path)

Data from the Parquet file:

,company_name,contact_person,date_issued,item_id,item_name,item_description,item_cost_price,item_retail_price,quantity,total_sale_value,gross_profit,overdue_status,ingest_ts
0,Apex Auto Group,Brent Barnes,2021-01-03,1-60559-539-X,VehicleMarketPro,High-Visibility,1.63507387,31.36233077,4,125.449323,118.91,Overdue,2024-07-23 08:29:00.836642
1,Apex Auto Group,Brent Barnes,2021-01-03,1-944086-93-5,AutoPromoBlitz,Performance-Driven,4.577482221,27.59476372,3,82.784291,69.05,Overdue,2024-07-23 08:29:00.836642
2,Apex Auto Group,Brent Barnes,2020-03-19,0-254-97850-9,EngineAdPro,Streamlined,32.35212531,38.12985263,2,76.259705,11.56,Overdue,2024-07-23 08:29:00.836642
3,Apex Auto Group,Brent Barnes,2020-03-19,1-60559-539-X,VehicleMarketPro,High-Visibility,1.63507387,31.36233077,1,31.362331,29.73,Overdue,2024-07-23 08:29:00.836642
4,Apex Auto Group,Brent Barnes,2020-03-19,0-575-31913-5,MotorAdFusion,Real-Time,18.36120796,210.9186898,4,843.674759,770.23,Overdue,2024-07-23 08:29:00.836642

,company_name,contact_person,date_issued,item_id,item_name,item_description,item_cost_price,item_retail_price,quantity,total_sale_value,gross_profit,overdue_status,ingest_ts
0,Apex Auto Group,Brent Barnes,2021-01-03,1-60559-539-X,VehicleMarketPro,High-Visibility,1.63507387,31.36233077,4,125.449323,118.91,Overdue,2024-07-23 08:29:00.836642
1,Apex Auto Group,Brent Barnes,2021-01-03,1-944086-93-5,AutoPromoBlitz,Performance-Driven,4.577482221,27.59476372,3,82.784291,69.05,Overdue,2024-07-23 08:29:00.836642
2,Apex Auto Group,Brent Barnes,2020-03-19,0-254-97850-9,EngineAdPro,Streamlined,32.35212531,38.12985263,2,76.259705,11.56,Overdue,2024-07-23 08:29:00.836642
3,Apex Auto Group,Brent Barnes,2020-03-19,1-60559-539-X,VehicleMarketPro,High-Visibility,1.63507387,31.36233077,1,31.362331,29.73,Overdue,2024-07-23 08:29:00.836642
4,Apex Auto Group,Brent Barnes,2020-03-19,0-575-31913-5,MotorAdFusion,Real-Time,18.36120796,210.9186898,4,843.674759,770.23,Overdue,2024-07-23 08:29:00.836642
...,...,...,...,...,...,...,...,...,...,...,...,...,...
55932,Venture Auto Mall,Tyler Atkins,2020-06-11,0-9968491-0-6,MotorPromoElite,Holistic,30.80013459,65.2611619,4,261.044648,137.84,Overdue,2024-07-23 08:29:00.836642
55933,Venture Auto Mall,Tyler Atkins,2020-06-11,0-19-815284-1,AutoAdBoost,High-Performance,13.38563993,81.67170578,4,326.686823,273.14,Overdue,2024-07-23 08:29:00.836642
55934,Venture Auto Mall,Tyler Atkins,2020-05-20,1-69029-927-4,AutoPromoSpot,Real-Time,2.769909948,63.80289597,4,255.211584,244.13,Overdue,2024-07-23 08:29:00.836642
55935,Venture Auto Mall,Tyler Atkins,2020-05-20,0-8208-9890-2,TurboPromoMaster,Campaign-Driven,28.97750736,59.57333241,3,178.719997,91.79,Overdue,2024-07-23 08:29:00.836642
55936,Venture Auto Mall,Tyler Atkins,2020-05-20,0-02-530216-7,EngineAdMax,Versatile,44.83229992,150.9138468,1,150.913847,106.08,Overdue,2024-07-23 08:29:00.836642

In [17]:

file_path = 'output/fact_table/fact_sales'
read_parquet_file(file_path)

Data from the Parquet file:

,invoice_id,account_id,item_id,date_issued,item_name,quantity,item_cost_price,item_retail_price,total_sale_value,total_cost_value,gross_profit,overdue_status,ingest_ts
0,1,1,1-60559-539-X,2021-01-03,VehicleMarketPro,4,1.63507387,31.36233077,125.449323,6.540295,118.909028,Overdue,2024-07-23 08:28:54.360685
1,1,1,1-944086-93-5,2021-01-03,AutoPromoBlitz,3,4.577482221,27.59476372,82.784291,13.732447,69.051844,Overdue,2024-07-23 08:28:54.360685
2,2,1,0-254-97850-9,2020-03-19,EngineAdPro,2,32.35212531,38.12985263,76.259705,64.704251,11.555455,Overdue,2024-07-23 08:28:54.360685
3,2,1,1-60559-539-X,2020-03-19,VehicleMarketPro,1,1.63507387,31.36233077,31.362331,1.635074,29.727257,Overdue,2024-07-23 08:28:54.360685
4,2,1,0-575-31913-5,2020-03-19,MotorAdFusion,4,18.36120796,210.9186898,843.674759,73.444832,770.229927,Overdue,2024-07-23 08:28:54.360685

,invoice_id,account_id,item_id,date_issued,item_name,quantity,item_cost_price,item_retail_price,total_sale_value,total_cost_value,gross_profit,overdue_status,ingest_ts
0,1,1,1-60559-539-X,2021-01-03,VehicleMarketPro,4,1.63507387,31.36233077,125.449323,6.540295,118.909028,Overdue,2024-07-23 08:28:54.360685
1,1,1,1-944086-93-5,2021-01-03,AutoPromoBlitz,3,4.577482221,27.59476372,82.784291,13.732447,69.051844,Overdue,2024-07-23 08:28:54.360685
2,2,1,0-254-97850-9,2020-03-19,EngineAdPro,2,32.35212531,38.12985263,76.259705,64.704251,11.555455,Overdue,2024-07-23 08:28:54.360685
3,2,1,1-60559-539-X,2020-03-19,VehicleMarketPro,1,1.63507387,31.36233077,31.362331,1.635074,29.727257,Overdue,2024-07-23 08:28:54.360685
4,2,1,0-575-31913-5,2020-03-19,MotorAdFusion,4,18.36120796,210.9186898,843.674759,73.444832,770.229927,Overdue,2024-07-23 08:28:54.360685
...,...,...,...,...,...,...,...,...,...,...,...,...,...
55932,10252,200,0-9968491-0-6,2020-06-11,MotorPromoElite,4,30.80013459,65.2611619,261.044648,123.200538,137.844109,Overdue,2024-07-23 08:28:54.360685
55933,10252,200,0-19-815284-1,2020-06-11,AutoAdBoost,4,13.38563993,81.67170578,326.686823,53.542560,273.144263,Overdue,2024-07-23 08:28:54.360685
55934,10253,200,1-69029-927-4,2020-05-20,AutoPromoSpot,4,2.769909948,63.80289597,255.211584,11.079640,244.131944,Overdue,2024-07-23 08:28:54.360685
55935,10253,200,0-8208-9890-2,2020-05-20,TurboPromoMaster,3,28.97750736,59.57333241,178.719997,86.932522,91.787475,Overdue,2024-07-23 08:28:54.360685
55936,10253,200,0-02-530216-7,2020-05-20,EngineAdMax,1,44.83229992,150.9138468,150.913847,44.832300,106.081547,Overdue,2024-07-23 08:28:54.360685

In [18]:

file_path = 'output/fact_table/fact_monthly_sales_summary'
read_parquet_file(file_path)

Data from the Parquet file:

,year,month,total_sales,total_costs,total_gross_profit,unique_customers,total_items_sold,ingest_ts
0,2020,6,536742.377095,250387.105120,286355.271975,181,11394,2024-07-23 08:28:56.983461
1,2020,11,516038.379040,247054.713076,268983.665964,182,11132,2024-07-23 08:28:56.983461
2,2020,3,246339.876864,116066.015765,130273.861099,158,5182,2024-07-23 08:28:56.983461
3,2020,9,496962.471886,233525.112601,263437.359285,176,10558,2024-07-23 08:28:56.983461
4,2020,12,600143.802399,280159.135054,319984.667345,179,12521,2024-07-23 08:28:56.983461

,year,month,total_sales,total_costs,total_gross_profit,unique_customers,total_items_sold,ingest_ts
0,2020,6,536742.377095,250387.105120,286355.271975,181,11394,2024-07-23 08:28:56.983461
1,2020,11,516038.379040,247054.713076,268983.665964,182,11132,2024-07-23 08:28:56.983461
2,2020,3,246339.876864,116066.015765,130273.861099,158,5182,2024-07-23 08:28:56.983461
3,2020,9,496962.471886,233525.112601,263437.359285,176,10558,2024-07-23 08:28:56.983461
4,2020,12,600143.802399,280159.135054,319984.667345,179,12521,2024-07-23 08:28:56.983461
5,2020,4,540999.890078,263055.639752,277944.250326,177,11504,2024-07-23 08:28:56.983461
6,2021,3,350759.427954,165894.714208,184864.713746,170,7452,2024-07-23 08:28:56.983461
7,2021,2,488976.682197,232583.502503,256393.179694,176,10332,2024-07-23 08:28:56.983461
8,2020,8,525136.392989,253467.072110,271669.320879,179,11129,2024-07-23 08:28:56.983461
9,2021,1,566909.839115,269010.667533,297899.171582,184,12135,2024-07-23 08:28:56.983461
10,2020,7,579073.147853,275426.740335,303646.407518,185,12506,2024-07-23 08:28:56.983461
11,2020,10,556797.764705,260864.192141,295933.572564,184,11535,2024-07-23 08:28:56.983461
12,2020,5,579917.214597,276962.592380,302954.622218,186,12307,2024-07-23 08:28:56.983461